import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-screen-xl flex flex-col  justify-between mx-auto p-2 min-h-screen'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
